version: "3.8"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fastapi-backend
        restart: always
        ports:
            - "8000:8000"
        env_file:
            - .env.prod
        depends_on:
            - mongo
            - redis-master

    mongo:
        image: mongo:6.0
        container_name: mongo-db
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - mongo_data:/data/db

    redis-master:
        image: redis:7
        container_name: redis-master
        restart: always

    redis-slave:
        image: redis:7
        container_name: redis-slave
        command: redis-server --slaveof redis-master 6379
        restart: always
        depends_on:
            - redis-master

volumes:
    mongo_data:
